### ISSUE TITLE
Opsdroid fails to start on windows if installed with anaconda

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid#494]
# Description
This issue was raised by @sbeesm on issue #477 - He is unable to run opsdroid when installed with anaconda present in the system. 

On an - probably not related - note I've also had issues with anaconda any my python3 install so maybe this could be an issue with conda?

## Steps to Reproduce
Install anaconda on a windows machine. Try to run opsdroid.

## Expected Functionality
Opsdroid runs.

## Experienced Functionality
Opsdroid runs.

```
PR #382 fixes #353 and adds windows support but I still get this error when I try to run opsdroid in windows:

> (C:\Anaconda3) C:\Users\HP>opsdroid
INFO opsdroid: ========================================
INFO opsdroid: Started application
INFO opsdroid: ========================================
INFO opsdroid: You can customise your opsdroid by modifying your configuration.yaml
INFO opsdroid: Read more at: http://opsdroid.readthedocs.io/#configuration
INFO opsdroid: Watch the Get Started Videos at: http://bit.ly/2fnC0Fh
INFO opsdroid: Install Opsdroid Desktop at:
https://github.com/opsdroid/opsdroid-desktop/releases
INFO opsdroid: ========================================
WARNING opsdroid.loader: No databases in configuration.This will cause skills which store things inmemory to lose data when opsdroid is restarted.
INFO opsdroid.loader: Cloning hello from remote repository
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\opsdroid.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\lib\site-packages\opsdroid\__main__.py", line 130, in main
    opsdroid.start_loop()
  File "c:\anaconda3\lib\site-packages\opsdroid\core.py", line 136, in start_loop
    self.loader.load_modules_from_config(self.config)
  File "c:\anaconda3\lib\site-packages\opsdroid\loader.py", line 257, in load_modules_from_config
    skills = self._load_modules('skill', config['skills'])
  File "c:\anaconda3\lib\site-packages\opsdroid\loader.py", line 307, in _load_modules
    self._install_module(config)
  File "c:\anaconda3\lib\site-packages\opsdroid\loader.py", line 336, in _install_module
    self._install_git_module(config)
  File "c:\anaconda3\lib\site-packages\opsdroid\loader.py", line 386, in _install_git_module
    config["branch"])
  File "c:\anaconda3\lib\site-packages\opsdroid\loader.py", line 98, in git_clone
    stderr=subprocess.PIPE)
  File "c:\anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
> 
I have installed it using pip3 in anaconda in my default python 3.6 environment.
```

## Versions
- **Opsdroid version:** dev
- **Python version:** 3.6
- **OS/Docker version:** Windows

## Configuration File
Please include your version of the configuration file bellow.

```yaml
# Your code goes here.

```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.

@sbeesm What windows version are you using? And would you like to add anything else to this report? 😃

**Comment by sbeesm** [comment]
I am using Windows 10 (Version 1709), and Conda 4.3.34

Opsdroid installs correctly but an error is raised as the service starts.

I think the error may be related to the loader file because error is raised after opsdroid.loader says "Cloning hello from remote repository", whereas at this point in the Ubuntu video tutorials, it simply connects to opsdroid.web and runs successfully.

`WARNING opsdroid.loader: No databases in configuration.This will cause skills which store things in memory to lose data when opsdroid is restarted.`
`INFO opsdroid.loader: Cloning hello from remote repository`
`Traceback (most recent call last):`
`....`

**Comment by jacobtomlinson** [comment]
Do you have the git command line installed?

**Comment by sbeesm** [comment]
Yes, but I am using the git command line tools from git bash only. I have not installed it over windows command prompt.

**Comment by jacobtomlinson** [comment]
Yes I think that's the problem. When opsdroid installs modules it needs to be able to run git from the command prompt.

I have two thoughts here:
- We should wrap this error in a better error message.
- Should we add a config option to allow you to point opsdroid to a git binary?

**Comment by sbeesm** [comment]
A config option would be really helpful! 😃

**Comment by sbeesm** [comment]
I have set the path of my default Python environment in Git Bash but the problem still persists.
Am I doing something wrong or it won't work that way?

```
HP@LAPTOP-6V5RSGD0 MINGW64 /
$ PATH=$PATH:/C/Anaconda3/envs/untitled/

HP@LAPTOP-6V5RSGD0 MINGW64 /
$ python --version
Python 3.6.3 :: Anaconda custom (64-bit)

HP@LAPTOP-6V5RSGD0 MINGW64 /
$ opsdroid
INFO opsdroid: ========================================
INFO opsdroid: Started application
INFO opsdroid: ========================================
INFO opsdroid: You can customise your opsdroid by modifying your configuration.yaml
INFO opsdroid: Read more at: http://opsdroid.readthedocs.io/#configuration
INFO opsdroid: Watch the Get Started Videos at: http://bit.ly/2fnC0Fh
INFO opsdroid: Install Opsdroid Desktop at:
https://github.com/opsdroid/opsdroid-desktop/releases
INFO opsdroid: ========================================
WARNING opsdroid.loader: No databases in configuration.This will cause skills which store things inmemory to lose data when opsdroid is restarted.
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\opsdroid.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\lib\site-packages\opsdroid\__main__.py", line 130, in main
    opsdroid.start_loop()
  File "c:\anaconda3\lib\site-packages\opsdroid\core.py", line 136, in start_loop
    self.loader.load_modules_from_config(self.config)
  File "c:\anaconda3\lib\site-packages\opsdroid\loader.py", line 266, in load_modules_from_config
    connectors = self._load_modules('connector', config['connectors'])
  File "c:\anaconda3\lib\site-packages\opsdroid\loader.py", line 313, in _load_modules
    module = self.import_module(config)
  File "c:\anaconda3\lib\site-packages\opsdroid\loader.py", line 49, in import_module
    "." + config["name"])
  File "c:\anaconda3\lib\importlib\util.py", line 88, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
  File "C:\Users\HP/.opsdroid\modules\opsdroid-modules\connector\shell\__init__.py", line 3, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'

```

**Comment by FabioRosado** [comment]
The issue might be on the shell connector as well I’ll try something and see if that helps

**Comment by FabioRosado** [comment]
@sbeesm  I have created a quick test to see if you are able to run opsdroid on windows. I would test it myself but I am away for two weeks in Poland and don't have access to a machine with windows installed.

Go to your documents(or desired folder) and could you please run the following on your command line:
```
git clone https://github.com/FabioRosado/connector-shell.git
git pull origin test
```

Your `__init__.py` file will be updated with the changes found [here](https://github.com/FabioRosado/connector-shell/blob/ad17fc287b7c4530ca3de87a1920ae8782337a82/__init__.py#L14)

Then on your `configuration.yaml` file add the following in the connector-shell section:
```yaml
connectors:
  - name: shell
     path: <path to the cloned connector-shell>
     no-cache: true
```
_Note: Careful with copy-pasting this code as I haven't checked the spacing properly(should work tho)_

Try running opsdroid again and let me know if that fixed the issue.

**Why this might fix the issue**
From the traceback, the issue seems to be in the `pwd` module. I did a quick search and seems that it doesn't work on windows. Using `os.environ` should be able to get your username (the pwd module was being used just for that propose).

**Note**
As I tested this quick fix on my mac I have noticed that opsdroid doesn't run due to an issue with one PR merged earlier. I will raise an issue about this later, but for a quick fix change the following line found [here](https://github.com/opsdroid/opsdroid/blob/a4c13f4f2cff2af5899b4bb0f5897eeaff98b249/opsdroid/message.py#L55) from:
`await self.connector.respond(response, room)`
to:
`await self.connector.respond(response)`

I hope this helps, again please let me know how it goes or if you need any further help with these instructions 👍

**Comment by sbeesm** [comment]
After updating the `__init__.py` and the connector-shell section in `configuration.yaml`, this happens:

```
HP@LAPTOP-6V5RSGD0 MINGW64 /
$ opsdroid
INFO opsdroid: ========================================
INFO opsdroid: Started application
INFO opsdroid: ========================================
INFO opsdroid: You can customise your opsdroid by modifying your configuration.yaml
INFO opsdroid: Read more at: http://opsdroid.readthedocs.io/#configuration
INFO opsdroid: Watch the Get Started Videos at: http://bit.ly/2fnC0Fh
INFO opsdroid: Install Opsdroid Desktop at:
https://github.com/opsdroid/opsdroid-desktop/releases
INFO opsdroid: ========================================
WARNING opsdroid.loader: No databases in configuration.This will cause skills which         store things inmemory to lose data when opsdroid is restarted.
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\opsdroid.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\lib\site-packages\opsdroid\__main__.py", line 130, in main
    opsdroid.start_loop()
  File "c:\anaconda3\lib\site-packages\opsdroid\core.py", line 136, in start_loop
    self.loader.load_modules_from_config(self.config)
  File "c:\anaconda3\lib\site-packages\opsdroid\loader.py", line 266, in load_modules_from_config
    connectors = self._load_modules('connector', config['connectors'])
  File "c:\anaconda3\lib\site-packages\opsdroid\loader.py", line 303, in _load_modules
    self.check_cache(config)
  File "c:\anaconda3\lib\site-packages\opsdroid\loader.py", line 76, in check_cache
    shutil.rmtree(config["install_path"])
  File "c:\anaconda3\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\anaconda3\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\anaconda3\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\anaconda3\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\anaconda3\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\anaconda3\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\HP/.opsdroid\\modules\\opsdroid-modules\\connector\\shell\\.git\\objects\\pack\\pack-fc055345fbe4896dd541660fd5caa3d5338322b1.idx'
```


But if I replace the existing `__init__.py` file in the Documents/.../opsdroid-modules/connector/shell with the new one (and not adding a path to the config file, i.e keeping the `configuration.yaml` file same), no error is shown but the opsdroid is stuck here:
```
HP@LAPTOP-6V5RSGD0 MINGW64 /
$ opsdroid
INFO opsdroid: ========================================
INFO opsdroid: Started application
INFO opsdroid: ========================================
INFO opsdroid: You can customise your opsdroid by modifying your configuration.yaml
INFO opsdroid: Read more at: http://opsdroid.readthedocs.io/#configuration
INFO opsdroid: Watch the Get Started Videos at: http://bit.ly/2fnC0Fh
INFO opsdroid: Install Opsdroid Desktop at:
https://github.com/opsdroid/opsdroid-desktop/releases
INFO opsdroid: ========================================
WARNING opsdroid.loader: No databases in configuration.This will cause skills which store things inmemory to lose data when opsdroid is restarted.
opsdroid> INFO opsdroid.web: ======== Running on http://127.0.0.1:8080 ========
(Press CTRL+C to quit)

```

**Comment by FabioRosado** [comment]
I’m happy to see that my quick fix seem to work (kind off), when I was looking at your traceback I was worried that you would have issues running opsdroid due to how the filepath is build in the `opsdroid.loader`.

This line: 
`PermissionError: [WinError 5] Access is denied: 'C:\\Users\\HP/.opsdroid\\modules\\opsdroid-modules\\connector\\shell\\.git\\objects`

Just made me sure that the issue exists also in the loader file(notice the wrong / used). 

As soon as I get home I’ll try to fix this issue by using the `os.path.join` method on the methods that join paths. This should fix the issue fully. Anyhow I’m happy that you can now use opsdroid in your windows system.

Please let me know if you encounter any further issues with it and if you need help with anything else 😀👍

**Comment by FabioRosado** [comment]
Btw out of curiosity how does your .opsdroid file shows and where is it located?

This folder is followed by the dot in order to hide it from the desktop  , does your show up? (I was reading and this could cause some issues on windows as well)

**Comment by sbeesm** [comment]
No, the .opsdroid folder does not show up on the desktop. But I can access it from C drive. `C:\Users\HP\.opsdroid` is the path to be exact. This folder is visible there.

**Comment by sbeesm** [comment]
@FabioRosado Regarding the change you suggested in `message.py` file [here](https://github.com/opsdroid/opsdroid/blob/a4c13f4f2cff2af5899b4bb0f5897eeaff98b249/opsdroid/message.py#L55)
from:
`await self.connector.respond(response, room)`
to:
`await self.connector.respond(response)`

The `message.py` file I have already has the latter part. This issue may have already been fixed.

**Comment by FabioRosado** [comment]
Okay great I wasn’t sure if the .opsdroid would cause any issue with windows or not. I guess if we fix all the path linking with that os.path.join it should make things work for you. As for the message.py bit I wrote that comment before digging deeper into the cause of the issue, once I found that the problem was with every single connector I pushed the changes to that test branch of the connector-shell that’s why it’s fixed 😀

**Comment by sbeesm** [comment]
Debug log:
```
INFO opsdroid: ========================================
INFO opsdroid: Started application
INFO opsdroid: ========================================
INFO opsdroid: You can customise your opsdroid by modifying your configuration.yaml
INFO opsdroid: Read more at: http://opsdroid.readthedocs.io/#configuration
INFO opsdroid: Watch the Get Started Videos at: http://bit.ly/2fnC0Fh
INFO opsdroid: Install Opsdroid Desktop at: 
https://github.com/opsdroid/opsdroid-desktop/releases
INFO opsdroid: ========================================
DEBUG opsdroid.loader: Loading modules from config...
WARNING opsdroid.loader: No databases in configuration.This will cause skills which store things inmemory to lose data when opsdroid is restarted.
DEBUG opsdroid.loader: Loading skill modules...
DEBUG opsdroid.loader: Updating hello...
DEBUG opsdroid.loader: b'Already up to date.'
DEBUG opsdroid.loader: Loaded skill: opsdroid-modules.skill.hello
DEBUG opsdroid.loader: Updating seen...
DEBUG opsdroid.loader: b'Already up to date.'
DEBUG opsdroid.loader: b'Collecting ago (from -r C:\\Users\\HP/.opsdroid\\modules\\opsdroid-modules\\skill\\seen\\requirements.txt (line 1))'
DEBUG opsdroid.loader: b'Installing collected packages: ago'
DEBUG opsdroid.loader: b'Successfully installed ago-0.0.92'
DEBUG opsdroid.loader: b'Target directory C:\\Users\\HP\\.opsdroid\\site-packages\\ago-0.0.92.dist-info already exists. Specify --upgrade to force replacement.'
DEBUG opsdroid.loader: b'Target directory C:\\Users\\HP\\.opsdroid\\site-packages\\ago.py already exists. Specify --upgrade to force replacement.'
DEBUG opsdroid.loader: b'Target directory C:\\Users\\HP\\.opsdroid\\site-packages\\__pycache__ already exists. Specify --upgrade to force replacement.'
DEBUG opsdroid.loader: Loaded skill: opsdroid-modules.skill.seen
DEBUG opsdroid.loader: Updating dance...
DEBUG opsdroid.loader: b'Already up to date.'
DEBUG opsdroid.loader: Loaded skill: opsdroid-modules.skill.dance
DEBUG opsdroid.loader: Updating loudnoises...
DEBUG opsdroid.loader: b'Already up to date.'
DEBUG opsdroid.loader: Loaded skill: opsdroid-modules.skill.loudnoises
DEBUG opsdroid.loader: Reloading module opsdroid-modules.skill.hello
DEBUG opsdroid.loader: Reloading module opsdroid-modules.skill.seen
DEBUG opsdroid.loader: Reloading module opsdroid-modules.skill.dance
DEBUG opsdroid.loader: Reloading module opsdroid-modules.skill.loudnoises
DEBUG opsdroid.loader: Loading connector modules...
DEBUG opsdroid.loader: Updating shell...
DEBUG opsdroid.loader: b'fatal: Not a git repository (or any of the parent directories): .git'
DEBUG opsdroid.loader: Loaded connector: opsdroid-modules.connector.shell
DEBUG opsdroid.loader: Updating websocket...
DEBUG opsdroid.loader: b'Already up to date.'
DEBUG opsdroid.loader: b'You must give at least one requirement to install (see "pip help install")'
DEBUG opsdroid.loader: Loaded connector: opsdroid-modules.connector.websocket
DEBUG opsdroid.core: Loaded 4 skills
DEBUG root: Loaded hello module
DEBUG root: Loaded seen module
DEBUG root: Loaded shell connector
DEBUG opsdroid-modules.connector.websocket: Starting Websocket connector
DEBUG opsdroid.web: Starting web server with host 127.0.0.1 and port 8080
DEBUG root: Connecting to shell
INFO opsdroid.web: ======== Running on http://127.0.0.1:8080 ========
(Press CTRL+C to quit)
DEBUG opsdroid.parsers.crontab: Running crontab skills
DEBUG asyncio: Using selector: SelectSelector
ERROR asyncio: Task exception was never retrieved
future: <Task finished coro=<ConnectorShell.listen() done, defined at C:\Users\HP/.opsdroid\modules\opsdroid-modules\connector\shell\__init__.py:64> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\HP/.opsdroid\modules\opsdroid-modules\connector\shell\__init__.py", line 70, in listen
    user_input = await async_input('', opsdroid.eventloop)
  File "C:\Users\HP/.opsdroid\modules\opsdroid-modules\connector\shell\__init__.py", line 41, in async_input
    reader, writer = await stdio(loop)
  File "C:\Users\HP/.opsdroid\modules\opsdroid-modules\connector\shell\__init__.py", line 28, in stdio
    writer_transport, writer_protocol = await loop.connect_write_pipe(FlowControlMixin, os.fdopen(0, 'wb'))
  File "c:\anaconda3\lib\asyncio\base_events.py", line 1115, in connect_write_pipe
    transport = self._make_write_pipe_transport(pipe, protocol, waiter)
  File "c:\anaconda3\lib\asyncio\base_events.py", line 333, in _make_write_pipe_transport
    raise NotImplementedError
NotImplementedError
ERROR asyncio: Task was destroyed but it is pending!
task: <Task pending coro=<parse_crontab() running at c:\anaconda3\lib\site-packages\opsdroid\parsers\crontab.py:16> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000001DD96513738>()]> cb=[gather.<locals>._done_callback(0)() at c:\anaconda3\lib\asyncio\tasks.py:616]>

```

**Comment by sbeesm** [comment]
```
ERROR asyncio: Task was destroyed but it is pending!
task: <Task pending coro=<parse_crontab() running at c:\anaconda3\lib\site-packages\opsdroid\parsers\crontab.py:16> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000001FA08603738>()]> cb=[gather.<locals>._done_callback(0)() at c:\anaconda3\lib\asyncio\tasks.py:616]>
```
I think this error at the bottom is encountered when I force kill the terminal when it hangs.

**Comment by FabioRosado** [comment]
It seems that currently the issue with the shell connector is due to the failure when it tried to import it from github.

Jacob just merged my PR to replace the use of pwd with os.environ to get the user data, could you try to replace the connector bit on your `configuration.yaml` with:
```
connectors: 
  - name: shell
     no-cache: true
```

Then run opsdroid again in order to get it downloaded and imported again from the official repo. Once that is done wait a bit as opsdroid takes a while to load all the modules and write hello or hi and see if it responds.

Usually when it shows the bit that says ==== running on ... ==== opsdroid is ready for input. 

Hopefully this will help you and make opsdroid run. Sorry for asking a lot of you but I’m still away in Poland and can’t test any of this on a Windows machine 😅

**Comment by jacobtomlinson** [comment]
I'm still not sure if the shell connector will work on Windows. 

You could try disabling the shell connector and just use the [websocket connector](https://github.com/opsdroid/connector-websocket) with [opsdroid desktop](https://github.com/opsdroid/opsdroid-desktop).

**Comment by sbeesm** [comment]
When I replace the connector in `configuration.yaml` with:
```
connectors: 
  - name: shell
    no-cache: true
```
Again a permission denied error is encountered:

```
$ opsdroid
INFO opsdroid: ========================================
INFO opsdroid: Started application
INFO opsdroid: ========================================
INFO opsdroid: You can customise your opsdroid by modifying your configuration.yaml
INFO opsdroid: Read more at: http://opsdroid.readthedocs.io/#configuration
INFO opsdroid: Watch the Get Started Videos at: http://bit.ly/2fnC0Fh
INFO opsdroid: Install Opsdroid Desktop at:
https://github.com/opsdroid/opsdroid-desktop/releases
INFO opsdroid: ========================================
WARNING opsdroid.loader: No databases in configuration.This will cause skills which store things inmemory to lose data when opsdroid is restarted.
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\opsdroid.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\lib\site-packages\opsdroid\__main__.py", line 130, in main
    opsdroid.start_loop()
  File "c:\anaconda3\lib\site-packages\opsdroid\core.py", line 136, in start_loop
    self.loader.load_modules_from_config(self.config)
  File "c:\anaconda3\lib\site-packages\opsdroid\loader.py", line 266, in load_modules_from_config
    connectors = self._load_modules('connector', config['connectors'])
  File "c:\anaconda3\lib\site-packages\opsdroid\loader.py", line 303, in _load_modules
    self.check_cache(config)
  File "c:\anaconda3\lib\site-packages\opsdroid\loader.py", line 76, in check_cache
    shutil.rmtree(config["install_path"])
  File "c:\anaconda3\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\anaconda3\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\anaconda3\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\anaconda3\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\anaconda3\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\anaconda3\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\HP/.opsdroid\\modules\\opsdroid-modules\\connector\\shell\\.git\\objects\\pack\\pack-496113884f27bb22ac819e3f0c6757f3770788e7.idx'
```

**Comment by sbeesm** [comment]
But keeping the default connector config:
```
connectors:
- name: shell
- name: websocket
```

Opsdroid does seem to work, but hangs after this:

```
$ opsdroid
INFO opsdroid: ========================================
INFO opsdroid: Started application
INFO opsdroid: ========================================
INFO opsdroid: You can customise your opsdroid by modifying your configuration.yaml
INFO opsdroid: Read more at: http://opsdroid.readthedocs.io/#configuration
INFO opsdroid: Watch the Get Started Videos at: http://bit.ly/2fnC0Fh
INFO opsdroid: Install Opsdroid Desktop at:
https://github.com/opsdroid/opsdroid-desktop/releases
INFO opsdroid: ========================================
WARNING opsdroid.loader: No databases in configuration.This will cause skills which store things inmemory to lose data when opsdroid is restarted.
opsdroid> INFO opsdroid.web: ======== Running on http://127.0.0.1:8080 ========
(Press CTRL+C to quit)
hello
hi
```
It does not respond to the messages and neither Ctrl+C works.

Is there any possibility that these issues are being encountered due to git-bash?
Because I am trying to run opsdroid through git-bash by adding a path to python environment.

**Comment by FabioRosado** [comment]
I looked at that config path before and mentioned that the issue might have been there. I didn't have enough time to explore that idea though. Also, I was reading today that the shutil module has some issues when run on windows - mostly that permissionError exception being thrown.

I'm coming back home tomorrow night and will still have three days of leave before going back to work so I should be able to try and solve this issue. 

I've also seen the #513 issue and would have to explore that library more as I never worked with it 😄 
When Im back home I will also be able to do proper testing on my windows machine to see if i get the same errors and what not.

**Comment by jacobtomlinson** [comment]
I'm going to close this as resolving #513 should resolve this.
